project:
  type: book
  output-dir: docs

book:
  title: "Spatial Data Workshop"
  author: "Marc Weber and Michael Dumelle"
  page-footer:
    left: |
      Spatial Data Workshop Materials written by Marc Weber and Michael Dumelle
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - foundations.qmd
    - visualization.qmd
    - geoprocessing.qmd
    - advanced_applications.qmd
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    code-link: true
    toc: true
    toc-depth: 4




