# Geoprocessing {#sec-geoprocessing}


Throughout this section, we ...

## Goals and Outcomes

* This is goal 1.
* This is goal 2.
* This is goal 3.

:::{.callout-note}
You may click on any of the functions in this book to be directed to their respective documentation. For example, clicking on `st_join()` takes you to the documentation page for the `st_join()` function on the `sf` website.
:::

## Spatial Subsetting 

## Spatial Join 

## Dissolve 

## Extract and Zonal Statistics 

## Fixing topology errors
- show typical fixes for topology errors

:::{.callout-note}
You may encounter errors like this when running geoprocessing operations like `st_join` in R:
```
Error in wk_handle.wk_wkb(wkb, s2_geography_writer(oriented
= oriented,  :  Loop 0 is not valid: Edge 772 crosses edge 774
```

Running `st_make_valid` might not fix.  

You may need to turn off spherical geometry - `sf_use_s2(TRUE)`, run `st_make_valid`, and then turn spherical geometry back on - `sf_use_s2(FALSE)`
See background on S2 [here](https://r-spatial.org/r/2020/06/17/s2.html) and discussion of S2 related issues [here](https://github.com/r-spatial/sf/issues/1771)
:::
