# Welcome {#sec-intro .unnumbered}

Hello and welcome! The purpose of this site is to provide workshop materials for the Spatial Data workshop at the 2023 EPA R User Group Workshop. Slides that accompany this workshop are available for download linked here by clicking the "Download raw file" button via the ellipsis or downward arrow symbol on the right side of the screen.

## Workshop Agenda

- 1:00pm - 1:45pm EDT: Introduction and Spatial Data Structures in R
- 1:45pm - 2:15pm EDT: Vector Data Model
- 2:15pm - 2:20pm Break
- 2:20pm - 2:35pm EDT: Raster Data Model
- 2:35pm - 2:45pm Break
- 2:45pm - 3:15pm EDT: 
- 3:15pm - 3:20pm Break
- 3:20pm - 3:45pm EDT: 
- 3:45pm - 4:15pm EDT: 
- 4:15pm - 4:45pm EDT: 
- 4:45pm - 5:00pm EDT:
  
## Author Introduction

Marc Weber is a geographer at the Pacific Ecological Systems Division (PESD) at the United States Environmental Protection Agency (USEPA). His work supports various aspects of the USEPA's National Aquatic Resource Surveys (NARS), which characterize the condition of waters across the United States, as he helped develop and maintains the StreamCat and LakeCat datasets.  His work focuses on spatial analysis in R and Python, Geographic Information Science (GIS), aquatic ecology, remote sensing, open source science and environmental modeling

Michael Dumelle is a statistician for the United States Environmental Protection Agency (USEPA). He works primarily on facilitating the survey design and analysis of USEPA's National Aquatic Resource Surveys (NARS), which characterize the condition of waters across the United States. His primary research interests are in spatial statistics, survey design, environmental and ecological applications, and software development.

## Set Up

The packages that we use throughout this workshop are listed below. To install and load them, run:

```{r}
#| eval: false
install.packages("ggplot2")
install.packages("cranlogs")
install.packages("sf")
```

## How to follow along with material

This workshop was built using [Quarto](https://quarto.org/) and [bookdown](https://github.com/rstudio/bookdown) and *rendered* to html.  If you are familiar with using git and GitHub, you can fork and clone [this repository](https://github.com/mhweber/spatialdata.epaR2023.git), or simply clone directly and open the corresponding .qmd files to follow along with material in RStudio.  You can also copy code snippets from the rendered book site and paste into your code files in RStudio.

[Quarto](https://quarto.org/) is a multi-language, next generation version of R Markdown from RStudio, with many new features and capabilities. Like R Markdown, Quarto uses Knitr to execute R code, and it can render most existing Rmd files without modification.  Like RMarkdown the benefits include:

- Allows for reproducible reporting from R
- You write your document in markdown and embed executable code chunks using the knitr syntax
- You can update your document at any time by re-knitting the code chunks and convert your document to a number of formats (i.e. html, pdf, word documents)
- We assume everyone in the workshop is familiar with using RStudio

## Disclaimer

The views expressed in this manuscript are those of the authors and do not necessarily represent the views or policies of the U.S. Environmental Protection Agency. Any mention of trade names, products, or services does not imply an endorsement by the U.S. government or the U.S. Environmental Protection Agency. The U.S. Environmental Protection Agency does not endorse any commercial products, services, or enterprises.
